language: python

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - pip install --upgrade pip wheel

install:
  - pip install -r test-requirements.txt
  - pip install .
    
python:
  - "3.4"
  - "3.5"

script:
  - py.test
  - PYVER=$(python -c "import sys; print('.'.join(map(str, sys.version_info[:2])))")
  - wget "https://github.com/getnikola/wheelhouse/archive/v${PYVER}.zip"
  - unzip v${PYVER}.zip
  - find wheelhouse-* -name '*.whl' | xargs -n1 -I '{}' sh -c "auditwheel show '{}'; echo ----------; echo ---------- "