language: python

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - pip install --upgrade pip wheel
  - pip -V

install:
  - pip install -r test-requirements.txt
  - pip install .
    
python:
  - "3.4"
  - "3.5"

script:
  - py.test
