language: python

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - pip install --upgrade pip wheel

install:
  - pip install -r test-requirements.txt
  - pip install .
    
python:
  - "3.4"
  - "3.5"

script:
  - py.test
  - bash tests/test-wheelhouses.sh

deploy:
  provider: pypi
  user: rmcgibbo
  password:
    secure: YJZgHf2goWyGIrssg/yUb+bADcy1J7ieFv69TMfldhGKhSrtgksju43KygiD6nrjvW+LhhVGIJipIk6a5/IMzqNvngmeWa2CidZy4kIO411LsakI6L5TkyyjDvFW2BuCBaWyrsMUyoFCKgdgaiEaecF+exgXoT+pWmGKZKZSGCcWUB9PldugaYQWsutxKCbh8LfFGC8x59Ck4eT2xpx4lbFb+jlJU8ZK1acwTS1D+Qb2a+Fdtn527BqkD9pNyT0a7LXFbEuDtsWeSggzBdxfhOR+n27op32Zctb9OAjReHFtzymk16dH61UyXwP7hPzYGMmQhgtOK0i25ZRh/wn0kgpyCLlp2e4/SItHDjOEyaFvw+sh9aKqY4i8wIjV/U1YNqMba/pNYMIOIECRFJOuElKlPgUEGUMGUXGbnQcDDWfppKyLzayoo+CUL0v//uUSopLxkkHGcniUr2LX0IDk6ukbVc7E1NEZXuEK8PX/hC4SjoKcj1e//fyA36d1brDS3T5lvxkUBm0A29U0Gfh3WoW0BJ3Vc95D3PukvAMYm73mZZq1cKJIvB3ui/kHn3885JJl3Ae1PldJNiQLcjWj6piuXz+L08CMy+HXpWKT+tpCI/kJ9QoaE+afpX1yOi700K3ukiwG+hiTBsptD9IjggCavI5mjkDk42RguGBokgg=
  on:
    tags: true
    repo: manylinux/auditwheel
