name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: CPython ${{ matrix.python }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python: "3.6"
          - python: "3.7"
          - python: "3.8"
          - python: "3.9"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install CPython ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install/fetch dependencies
        run: |
          set -exuo pipefail
          pip install --upgrade pip setuptools
          ./tests/install.sh

      - name: Run tests
        run: ./tests/travis.sh
