name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: CPython ${{ matrix.python }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python: "3.6"
          - python: "3.7"
          - python: "3.8"
          - python: "3.9"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install CPython ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install/fetch dependencies
        run: |
          set -exuo pipefail
          pip install --upgrade pip setuptools
          pip install -r test-requirements.txt
          pip install tox codecov
          pip install -e .
          # pull manylinux images that will be used, this helps passing tests which would otherwise timeout.
          python -c $'from tests.integration.test_manylinux import MANYLINUX_IMAGES\nfor image in MANYLINUX_IMAGES.values():\n    print(image)' | xargs -L 1 docker pull

      - name: Run tests
        run: ./tests/travis.sh
